import React, {FC} from 'react'

import IconName from './IconName'
import IconProps from './IconProps'

import {
  AngleDownIcon,
  AngleUpIcon,
  AngleRightIcon,
  AngleLeftIcon,
  AngleSmallDownIcon,
  AngleSmallUpIcon,
  AngleSmallLeftIcon,
  AngleSmallRightIcon,
  ArrowDownIcon,
  ArrowUpIcon,
  ArrowRightIcon,
  ArrowLeftIcon,
  ArrowSmallDownIcon,
  ArrowSmallUpIcon,
  ArrowSmallRightIcon,
  ArrowSmallLeftIcon,
  AttentionIcon,
  BankIcon,
  CalendarIcon,
  CardIcon,
  CheckIcon,
  ClockIcon,
  CrossIcon,
  AngleDoubleLeftSmallIcon,
  AngleDoubleRightSmallIcon,
  AngleDoubleLeftIcon,
  AngleDoubleRightIcon,
  DownloadIcon,
  DotsHIcon,
  DotsVIcon,
  EnvelopeIcon,
  EyeClosedIcon,
  EyeOpenedIcon,
  FacebookIcon,
  FileIcon,
  FilterIcon,
  FilterActiveIcon,
  HamburgerIcon,
  InstagramIcon,
  LocationIcon,
  LoginIcon,
  LogoutIcon,
  MastercardIcon,
  McscIcon,
  MirAcceptIcon,
  MirIcon,
  MobileIcon,
  OkIcon,
  PassportIcon,
  PciDssIcon,
  PhoneIcon,
  PlayIcon,
  PlusIcon,
  PowerIcon,
  PrintIcon,
  PercentIcon,
  QuestionIcon,
  QiwiIcon,
  ReceiptIcon,
  RefundIcon,
  RepeatIcon,
  SearchIcon,
  SendIcon,
  SettingsIcon,
  ShareIcon,
  StarIcon,
  TerminalIcon,
  TerminalClientIcon,
  TwitterIcon,
  VisaIcon,
  VisaVerifiedIcon,
  VkIcon,
  UserIcon,
  YoutubeIcon,
} from './icons'

const Icons: { [name in IconName]: FC } = {
  'angle-right': AngleRightIcon,
  'angle-left': AngleLeftIcon,
  'angle-up': AngleUpIcon,
  'angle-down': AngleDownIcon,
  'angle-double-right-small': AngleDoubleRightSmallIcon,
  'angle-double-left-small': AngleDoubleLeftSmallIcon,
  'angle-double-right': AngleDoubleRightIcon,
  'angle-double-left': AngleDoubleLeftIcon,
  'angle-small-right': AngleSmallRightIcon,
  'angle-small-left': AngleSmallLeftIcon,
  'angle-small-up': AngleSmallUpIcon,
  'angle-small-down': AngleSmallDownIcon,
  'arrow-right': ArrowRightIcon,
  'arrow-left': ArrowLeftIcon,
  'arrow-up': ArrowUpIcon,
  'arrow-down': ArrowDownIcon,
  'arrow-small-right': ArrowSmallRightIcon,
  'arrow-small-left': ArrowSmallLeftIcon,
  'arrow-small-up': ArrowSmallUpIcon,
  'arrow-small-down': ArrowSmallDownIcon,
  attention: AttentionIcon,
  bank: BankIcon,
  calendar: CalendarIcon,
  card: CardIcon,
  check: CheckIcon,
  clock: ClockIcon,
  cross: CrossIcon,
  download: DownloadIcon,
  'dots-h': DotsHIcon,
  'dots-v': DotsVIcon,
  envelope: EnvelopeIcon,
  'eye-closed': EyeClosedIcon,
  'eye-opened': EyeOpenedIcon,
  facebook: FacebookIcon,
  file: FileIcon,
  filter: FilterIcon,
  'filter-active': FilterActiveIcon,
  hamburger: HamburgerIcon,
  instagram: InstagramIcon,
  location: LocationIcon,
  login: LoginIcon,
  logout: LogoutIcon,
  mastercard: MastercardIcon,
  mcsc: McscIcon,
  'mir-accept': MirAcceptIcon,
  mir: MirIcon,
  mobile: MobileIcon,
  ok: OkIcon,
  passport: PassportIcon,
  'pci-dss': PciDssIcon,
  percent: PercentIcon,
  phone: PhoneIcon,
  play: PlayIcon,
  plus: PlusIcon,
  power: PowerIcon,
  print: PrintIcon,
  question: QuestionIcon,
  qiwi: QiwiIcon,
  receipt: ReceiptIcon,
  refund: RefundIcon,
  repeat: RepeatIcon,
  search: SearchIcon,
  send: SendIcon,
  settings: SettingsIcon,
  share: ShareIcon,
  star: StarIcon,
  terminal: TerminalIcon,
  'terminal-client': TerminalClientIcon,
  twitter: TwitterIcon,
  user: UserIcon,
  visa: VisaIcon,
  'visa-verified': VisaVerifiedIcon,
  vk: VkIcon,
  youtube: YoutubeIcon,
}

const Icon: FC<IconProps> = (props) => {
  const RenderedIcon = Icons[props.name]
  return (
    <RenderedIcon/>
  )
}

export default Icon
