export type IconName =
  'angle-right' |
  'angle-left' |
  'angle-up' |
  'angle-down' |
  'angle-double-right-small' |
  'angle-double-left-small' |
  'angle-double-right' |
  'angle-double-left' |
  'angle-small-right' |
  'angle-small-left' |
  'angle-small-up' |
  'angle-small-down' |
  'arrow-right' |
  'arrow-left' |
  'arrow-up' |
  'arrow-down' |
  'arrow-small-right' |
  'arrow-small-left' |
  'arrow-small-up' |
  'arrow-small-down' |
  'attention' |
  'backward' |
  'bank' |
  'calendar' |
  'card' |
  'check' |
  'clock' |
  'cross' |
  'dots-h' |
  'dots-v' |
  'download' |
  'envelope' |
  'eye-closed' |
  'eye-opened' |
  'facebook' |
  'file' |
  'filter' |
  'filter-active' |
  'forward' |
  'hamburger' |
  'instagram' |
  'location' |
  'login' |
  'logout' |
  'mastercard' |
  'mcsc' |
  'mir' |
  'mir-accept' |
  'mobile' |
  'ok' |
  'passport' |
  'pci-dss' |
  'percent' |
  'phone' |
  'play' |
  'plus' |
  'plus-circle' |
  'power' |
  'print' |
  'qiwi' |
  'question' |
  'receipt' |
  'refund' |
  'repeat' |
  'search' |
  'send' |
  'settings' |
  'share' |
  'sort-asc' |
  'sort-desc' |
  'star' |
  'success' |
  'terminal' |
  'terminal-client' |
  'twitter' |
  'user' |
  'visa' |
  'visa-verified' |
  'vk' |
  'waiting' |
  'youtube'

export default IconName
