# This is a Github Workflow that runs tests on any push or pull request.
# If the tests pass and this is a push to the master branch it also runs Semantic Release.
name: CI
on:
  push:
    branches: ['**']
    tags: ['zbr-rebuild.*']
  pull_request:

permissions: {}

jobs:
  init:
    name: init
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      checksum: ${{ steps.checksum.outputs.checksum }}
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Get src checksum
        id: checksum
        run: echo checksum=${{ hashFiles('yarn.lock', '*.json', 'packages/*/*.json', 'packages/*/src/main/ts/**/*', 'packages/*/src/main/webapp/**/*') }} >> "$GITHUB_OUTPUT"

  build:
    name: build
    needs: init
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Download artifact
        uses: qiwi-forks/action-download-artifact@v2
        with:
          name: artifact-${{ needs.init.outputs.checksum }}
          workflow: 'ci.yaml'
          workflow_conclusion: false
          nothrow: true
          search_artifacts: true
          search_depth: 20
      - run: ls -l

      - name: Check artifact
        id: check-artifact
        run: echo exists=$([ -e "artifact.tar" ] && echo true || echo false) >> "$GITHUB_OUTPUT"

      - uses: actions/setup-node@v4
        if: ${{ steps.check-artifact.outputs.exists == 'false' }}
        with:
          cache: 'yarn'
          node-version: 20

      - name: Install deps
        if: ${{ steps.check-artifact.outputs.exists == 'false' }}
        run: yarn

      - name: Build
        if: ${{ steps.check-artifact.outputs.exists == 'false' }}
        run: |
          yarn build
          tar -cvf artifact.tar package.json packages/*/target

      - name: Save artifact
        uses: actions/upload-artifact@v4
        if: ${{ steps.check-artifact.outputs.exists == 'false' }}
        with:
          name: artifact-${{ needs.init.outputs.checksum }}
          retention-days: 30
          path: artifact.tar

  test_push:
    needs: [build, init]
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'

      - name: Download artifact
        uses: qiwi-forks/action-download-artifact@v2
        with:
          name: artifact-${{ needs.init.outputs.checksum }}
          workflow: 'ci.yaml'
          workflow_conclusion: false
          nothrow: true
          search_artifacts: true
          search_depth: 20

      - name: Unpack artifact
        run: tar -xvf artifact.tar

      - name: Install
        run: yarn

      - name: Lint
        run: yarn lint

  test_pr:
    if: github.event_name == 'pull_request'
    needs: [build, init]
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node-version: [ 16, 22 ]
    name: Test (Node v${{ matrix.node-version }}, OS ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      actions: read
    env:
      # enables fetch for Node 16
      NODE_OPTIONS: '--experimental-fetch'
      YARN_IGNORE_NODE: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Download artifact
        uses: qiwi-forks/action-download-artifact@v2
        with:
          name: artifact-${{ needs.init.outputs.checksum }}
          workflow: 'ci.yaml'
          workflow_conclusion: false
          nothrow: true
          search_artifacts: true
          search_depth: 20

      - name: Unpack artifact
        run: tar -xvf artifact.tar

      - name: Install
        run: yarn

      - name: Docker pull
        if: matrix.node-version == '16'
        run: ./node_modules/.bin/concurrently --max-parallel 2 \
          "docker pull browserless/chrome@sha256:4655517b70d598367f363e15fa311ea514879f6b4908ba9199d6714d6f8269a3" \
          "docker pull nginx@sha256:480868e8c8c797794257e2abd88d0f9a8809b2fe956cbfbc05dcc0bca1f7cd43"

      - name: Lint
        if: matrix.node-version == '22'
        run: yarn lint

      - name: Visual tests
        if: matrix.node-version == '16'
        run: yarn test

      - name: Save failure results
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: screenshots-${{ needs.init.outputs.checksum }}
          retention-days: 1
          path: |
            packages/*/src/main/resources/screenshots/*.new.png
            packages/*/src/main/resources/screenshots/*.diff.png

  release_build:
    name: 'Release: receive & pack'
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: [test_push, init]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'yarn'

      - name: Receive
        id: receive
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_USER: 'qiwibot'
        run: npx zx-bulk-release --receive

      - name: Upload context
        uses: actions/upload-artifact@v4
        with:
          name: zbr-context-${{ github.run_id }}
          path: zbr-context.json
          retention-days: 1

      - name: Download build artifact
        uses: qiwi-forks/action-download-artifact@v2
        with:
          name: artifact-${{ needs.init.outputs.checksum }}
          workflow: 'ci.yaml'
          workflow_conclusion: false
          nothrow: true
          search_artifacts: true
          search_depth: 20

      - name: Unpack build artifact
        run: tar -xvf artifact.tar

      - name: Install deps
        run: yarn
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false

      - name: Pack
        if: steps.receive.outputs.status == 'proceed'
        run: npx zx-bulk-release --pack --no-build --no-test

      - name: Upload parcels
        if: steps.receive.outputs.status == 'proceed'
        uses: actions/upload-artifact@v4
        with:
          name: parcels-${{ github.run_id }}
          path: parcels/
          retention-days: 1

  release_deliver:
    name: 'Release: verify & deliver'
    needs: [release_build]
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Download context
        id: context
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: zbr-context-${{ github.run_id }}
          path: .

      - name: Download parcels
        id: download
        if: steps.context.outcome == 'success'
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: parcels-${{ github.run_id }}
          path: parcels-unverified/

      - name: Verify
        if: steps.context.outcome == 'success' && steps.download.outcome == 'success'
        run: npx zx-bulk-release --verify parcels-unverified/:parcels/

      - name: Deliver
        if: steps.context.outcome == 'success' && steps.download.outcome == 'success'
        env:
          NPM_OIDC: true
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_USER: 'qiwibot'
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_EMAIL: 'opensource@qiwi.com'
          GIT_COMMITTER_EMAIL: 'opensource@qiwi.com'
          GIT_AUTHOR_NAME: 'QIWI Bot'
          GIT_COMMITTER_NAME: 'QIWI Bot'
        run: npx zx-bulk-release --deliver

      - name: Update delivery status
        if: steps.context.outcome == 'success' && steps.download.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: parcels-${{ github.run_id }}
          path: parcels
          overwrite: true
          retention-days: 1
